/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-application-conventions")
}

dependencies {
    implementation(project(":core"))
}

application {
    // Define the main class for the application.
    mainClass = "org.example.app.App"
}
